### ISSUE TITLE
npm run build: [vite]: Rollup failed to resolve import "graphql" from "node_modules/@urql/core/dist/urql-core.mjs".

### ISSUE THREAD

**Issue by bbigras** [DustinJSilk/qwik-urql#35]
Do I need to add it to `build.rollupOptions.external`?

```
❯ npm run build

> build
> qwik build


tsc --incremental --noEmit
vite build
vite build -c adaptors/express/vite.config.ts
eslint src/**/*.ts*

vite v3.2.2 building for production...
✓ 67 modules transformed.
[vite]: Rollup failed to resolve import "graphql" from "node_modules/@urql/core/dist/urql-core.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "graphql" from "node_modules/@urql/core/dist/urql-core.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///home/bbigras/dev/luxor/app-tech2/node_modules/vite/dist/node/chunks/dep-c842e491.js:46705:19)
    at onwarn (file:///home/bbigras/dev/luxor/app-tech2/node_modules/vite/dist/node/chunks/dep-c842e491.js:46476:13)
    at Object.onwarn (file:///home/bbigras/dev/luxor/app-tech2/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
    at ModuleLoader.handleResolveId (file:///home/bbigras/dev/luxor/app-tech2/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
    at file:///home/bbigras/dev/luxor/app-tech2/node_modules/rollup/dist/es/shared/rollup.js:22119:26
```

**Comment by DustinJSilk** [comment]
Have you installed graphql?

**Comment by bbigras** [comment]
I didn't sorry about that.

Now I have `TypeError: F is not a function` when building with express, but I'm having a similar problem with another project not using qwik-urql.

**Comment by bbigras** [comment]
and thanks :)
